# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
#  - osx
julia:
  - 1
notifications:
  email: false
script:
  - julia --color=yes -e 'using Pkg; Pkg.build()'
  - julia --check-bounds=yes --color=yes -e 'using Pkg; Pkg.test(coverage=true)'
branches:
  only:
    - master
after_success:
  - julia -e 'using Pkg; Pkg.add("Documenter")'
  - julia -e 'using Pkg; cd(Pkg.dir("RiskAdjustedLinearizations")); include(joinpath("docs", "make.jl"))'
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("RiskAdjustedLinearizations")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("RiskAdjustedLinearizations")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

# jobs:
#   include:
#     - stage: "Documentation"
#       julia: 1
#       os: linux
#       script:
#         - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
#                                                Pkg.instantiate()'
#         - julia --project=docs/ docs/make.jl
